version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: elearn_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: elearn_backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      - DB_HOST=postgres
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
      - uploads_data:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: elearn_frontend
    restart: always
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data:
  uploads_data:
